# Numpy module

In [ ]:
pip install numpy

In [20]:
import numpy as np

# Creating an Array

In [ ]:
a = np.array([435,534,34,34,34,43])

print(a,type(a))

In [ ]:
# converting list into array

l1 = [10,20,30,40.65,"dffd",60]

a = np.array(l1)

print(a,type(a),a.dtype)

In [ ]:
print(a)

In [ ]:
print(a.ndim)   #check dimension

In [ ]:
a = np.array([12,45,6,67,78,45])


print(a,type(a))

In [ ]:
# for checking the shape or values

print(a.shape)

In [ ]:
b = a.reshape(3,2)   # rows  # columns

print(b)

In [ ]:
b.ndim

In [ ]:
b.shape

# 2D

In [ ]:
list1 = [[234,34,55],[54,74,34],[34,65,34],[34,35,67]]

# converting list to 2D
ab = np.array(list1)

print(ab)

In [ ]:
ab.ndim

In [ ]:
ab.shape

In [ ]:
print(ab.reshape(2,6))

# indexing and scling in array

In [ ]:
a

In [ ]:
a[2]

In [ ]:
a[-1]

In [ ]:
a[0]

In [ ]:
a[2:4]    # 2,3

In [ ]:
a[:]

In [ ]:
a[-4:-1]    #-4,-3,-2

In [ ]:
a[2:8:2]

In [ ]:
a[0:10:4]

In [ ]:
a

In [ ]:
a[0] = 100

In [ ]:
a

In [ ]:
t2 = [[23,323],[34,34]]

t1 = ((10,20),(30,40))

print(t1,type(t1))

a = np.array(t1)
a

In [ ]:
a.ndim

In [ ]:
a.shape

# 3D

In [ ]:
t1 = ( ((10,20,15),(30,40,25)),( (50,60,18),(70,80,35) ))

t2 = [[[34,345,44],[435,53,45]],[[45,5,454],[45,34,534]]]

print(t1,type(t2))

a=np.array(t2)

print(a)

In [ ]:
a.ndim

In [ ]:
a.shape   # 12   -  3,2,2

In [ ]:
b = a.reshape(6,2)

In [ ]:
b

In [ ]:
b.ndim

# COPY

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

# VIEW

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()

arr[0] = 42

print(arr)
print(x)

In [ ]:
The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

# Sort

In [ ]:
arr = np.array([1, 2, 3, 4, 5,4,5])

arr.sort()

arr

In [ ]:
list1 = [[234,34,55],[54,74,34]]


a = np.array(list1)
a.sort()

print(a)

# arange()

In [ ]:
a = np.arange(10)  # 10 - end value

print(a,type(a))

In [ ]:
a.ndim

In [ ]:
a = np.arange(50,62)    # 50 - start    62-end
a

In [ ]:
a.ndim


In [ ]:
a = np.arange(10,22,2) #10-  22  2 - step size
a

In [ ]:
b = a.reshape(2,3)
b

In [ ]:
b.ndim

In [ ]:
c= a.reshape(2,3,1)
c

In [ ]:
c.ndim

In [ ]:
c.shape

# isin()

In [ ]:
To check any value is present or not in the array

In [ ]:
list1 = [[234,34,55],[54,74,34]]

a = np.array(list1)

b = np.isin(34,a)

b

# where()

In [ ]:
It is used to find the index number of any value

In [ ]:
arr = np.array([1, 2, 3, 4, 5,4,5])

n = 3

b =  np.where(arr == n)

b

In [ ]:
list1 = [[234,34,55],[54,74,34]]

a = np.array(list1)

n = 34

b = np.where(a == n)

b

In [ ]:
a

# zeros()

In [ ]:
a = np.zeros(5)
print(a)

In [ ]:
a.ndim

In [ ]:
a = np.zeros((3,3))
a

In [ ]:
a.ndim

In [ ]:
a=np.zeros((2,3), dtype=int)
a

# ones()

In [ ]:
a = np.ones(12)
a

In [ ]:
a.reshape(3,4)

In [ ]:
a = np.ones((4,5), dtype=int)
a

In [ ]:
a.reshape(2,5,2)

# Numpy--Arithmetic Operations (OR) Matrix Operations

In [3]:
# 1D array

a = np.array([10,20,30,40])
b = np.array([1,2,3,4])

d = np.add(a,b)

print(d)

[11 22 33 44]


In [4]:
# 2d array

a = np.array([[10,20],[30,40]])
b = np.array([[1,2],[3,4]])

d = np.add(a,b)

print(d)

[[11 22]
 [33 44]]


In [ ]:
d.ndim

In [5]:
# arth oper

a = np.array([[10,20],[30,40]])
b = np.array([[1,2],[3,4]])

#print(a)
#print(b)

c = a + b

print(c,type(c))



[[11 22]
 [33 44]] <class 'numpy.ndarray'>


In [6]:
a = np.array([[10,20],[30,40],[34,56]])
b = np.array([[1,2],[3,4],[5,6]])

#print(a)
#print(b)

c = np.subtract(a,b)

print(c)

[[ 9 18]
 [27 36]
 [29 50]]


In [7]:
a = np.array([[10,20],[30,40],[34,56]])
b = np.array([[1,2],[3,4],[5,6]])

#print(a)
#print(b)

c = a - b

print(c,type(c))



[[ 9 18]
 [27 36]
 [29 50]] <class 'numpy.ndarray'>


In [8]:
a = np.array([[10,20],[30,40]])
b = np.array([[1,2],[3,4]])

#print(a)
#print(b)

c = np.multiply(a,b)

print(c)

[[ 10  40]
 [ 90 160]]


In [9]:
a = np.array([[10,20],[30,40]])
b = np.array([[1,2],[3,4]])

#print(a)
#print(b)

c = a * b

print(c)

[[ 10  40]
 [ 90 160]]


In [10]:
a = np.array([[10,20],[30,40]])
b = np.array([[1,2],[3,4]])

#print(a)
#print(b)

c = np.divide(a,b)

print(c)

[[10. 10.]
 [10. 10.]]


In [11]:
c = a / b

print(c)

[[10. 10.]
 [10. 10.]]


In [ ]:
40/4

In [12]:
a = np.array([[10,20],[30,40]])
b = np.array([[1,2],[3,4]])

#print(a)
#print(b)

c = np.floor_divide(a,b)

print(c)

[[10 10]
 [10 10]]


In [13]:
d = a // b

print(d)

[[10 10]
 [10 10]]


In [14]:
a = np.array([[11,3],[30,40]])
b = np.array([[1,2],[3,4]])

#print(a)
#print(b)

c = np.mod(a,b)

print(c)

[[0 1]
 [0 0]]


In [15]:
a = np.array([[11,3],[30,40]])
b = np.array([[1,2],[3,4]])


c = a % b

print(c)

[[0 1]
 [0 0]]


In [ ]:
40 % 4

In [16]:
a = np.array([[10,20],[30,40]])
b = np.array([[1,2],[3,4]])
 
#print(a)
#print(b)

c = np.power(a,b)

print(c)

[[     10     400]
 [  27000 2560000]]


In [17]:
a = np.array([[10,20],[30,40]])
b = np.array([[1,2],[3,4]])


c = a ** b

print(c)

[[     10     400]
 [  27000 2560000]]


In [ ]:
10**1

In [ ]:
# 20 **2 = 20 * 20

#20 ** 2

40 * 40 * 40 * 40

In [ ]:
# 30 ** 3 = 30 * 30 * 30

In [ ]:
30 ** 3

# 1D, 2D, 3D

In [23]:
_1d = [54,54,67,766,676]

_2d = [[34,76,76],[65,76,65]]

_3d = [[[34,23],[435,322]],[[67,86],[76,44]]]


#print(_3d, type(_3d))

a = np.array(_3d)
b = np.array(_2d)


#print(a, type(a))


print(b)


[[34 76 76]
 [65 76 65]]


In [ ]:
d.shape

In [ ]:
d = d.reshape(2,4)
d

In [ ]:
d.ndim
